[project]
name = "odoo-addons-oca-contract"
version = "17.0.20240410.0"
dependencies = [
    "odoo-addon-contract>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
